// ACCESORIOS FRAME PVC DEPOT — edita nombre, detalle, precio e imagen
// Fotos: img/accesorios/01.jpg … 30.jpg

window.STOCK_ACCESORIOS = [
  { id: 1, categoria: "perfiles proyectante", nombre: "Marco Fijo", detalle: "Sección 66×60 mm · tira 5,8 mt.", precio: 23091, precios: { blanco: 23091, "roble-nogal": 29678, "antracita-negro": 32655 }, imagen: "img/accesorios/01.jpg" },
  { id: 2, categoria: "perfiles proyectante", nombre: "Poste T", detalle: "Perfil poste T, sección 83×60 mm · tira 5,8 mt.", precio: 26676, precios: { blanco: 26676, "roble-nogal": 35152, "antracita-negro": 38363 }, imagen: "img/accesorios/02.jpg" },
  { id: 3, categoria: "perfiles proyectante", nombre: "Hoja Interior", detalle: "Perfil hoja interior, sección 57×60 mm · tira 5,8 mt.", precio: 27676, precios: { blanco: 27676, "roble-nogal": 35593, "antracita-negro": 38002 }, imagen: "img/accesorios/03.jpg" },
  { id: 4, categoria: "perfiles proyectante", nombre: "Hoja Ventana Exterior", detalle: "Perfil hoja exterior, sección 76×60 mm · tira 5,8 mt.", precio: 27856, precios: { blanco: 27856, "roble-nogal": 39312, "antracita-negro": 42111 }, imagen: "img/accesorios/04.jpg" },
  { id: 5, categoria: "perfiles proyectante", nombre: "Hoja Puerta Interior Grande", detalle: "Perfil hoja puerta interior grande, sección 90×60 mm · tira 5,8 mt.", precio: 36556, precios: { blanco: 36556, "roble-nogal": 52503, "antracita-negro": 56177 }, imagen: "img/accesorios/05.jpg" },
  { id: 6, categoria: "perfiles proyectante", nombre: "Hoja Puerta Exterior", detalle: "Perfil hoja puerta exterior, sección 110×60 mm · tira 5,8 mt.", precio: 35288, precios: { blanco: 35288, "roble-nogal": 52503, "antracita-negro": 56177 }, imagen: "img/accesorios/06.jpg" },
  { id: 31, categoria: "perfiles proyectante", nombre: "Doble Junquillos", detalle: "Junquillo doble, sección 20×21 mm · tira 5,8 mt.", precio: 6370, precios: { blanco: 6370, "roble-nogal": 10075, "antracita-negro": 10782 }, imagen: "img/accesorios/31.jpg" },
  { id: 32, categoria: "perfiles proyectante", nombre: "Monolitico Junquillos", detalle: "Junquillo monolítico 10 mm, sección 30×21 mm · tira 5,8 mt.", precio: 8258, precios: { blanco: 8258, "roble-nogal": 12779, "antracita-negro": 13676 }, imagen: "img/accesorios/32.jpg" },

  { id: 7, categoria: "perfiles correderas", nombre: "Marco Corredera Doble Riel", detalle: "Marco corredera doble riel, sección 70×53 mm · tira 5,8 mt.", precio: 28028, precios: { blanco: 28028, "roble-nogal": 39599, "antracita-negro": 42372 }, imagen: "img/accesorios/07.jpg" },
  { id: 8, categoria: "perfiles correderas", nombre: "Marco Corredera Triple Riel", detalle: "Marco corredera triple riel, sección 126×54 mm · tira 5,8 mt.", precio: 55370, precios: { blanco: 55370, "roble-nogal": 66865, "antracita-negro": 69805 }, imagen: "img/accesorios/08.jpg" },
  { id: 9, categoria: "perfiles correderas", nombre: "Hoja Corredera", detalle: "Perfil hoja corredera, sección 47×79 mm · tira 5,8 mt.", precio: 30659, precios: { blanco: 30659, "roble-nogal": 43472, "antracita-negro": 46097 }, imagen: "img/accesorios/09.jpg" },
  { id: 10, categoria: "perfiles correderas", nombre: "Grand Hoja Corredera", detalle: "Perfil grand hoja corredera para vanos grandes · tira 5,8 mt.", precio: 30659, precios: { blanco: 30659, "roble-nogal": 43472, "antracita-negro": 46097 }, imagen: "img/accesorios/10.jpg" },
  { id: 11, categoria: "perfiles correderas", nombre: "Traslapo", detalle: "Perfil traslapo corredera, sección 55,3×40 mm · tira 5,8 mt.", precio: 8809, precios: { blanco: 8809, "roble-nogal": 18430, "antracita-negro": 19721 }, imagen: "img/accesorios/11.jpg" },
  { id: 12, categoria: "perfiles correderas", nombre: "Sliding Rail", detalle: "Riel corredera para hoja deslizante · tira 5,8 mt.", precio: 10443, imagen: "img/accesorios/12.jpg" },
  { id: 33, categoria: "perfiles correderas", nombre: "Doble Junquillos", detalle: "Junquillo doble, sección 20×21 mm · tira 5,8 mt.", precio: 5512, precios: { blanco: 5512, "roble-nogal": 9162, "antracita-negro": 9770 }, imagen: "img/accesorios/33.jpg" },
  { id: 34, categoria: "perfiles correderas", nombre: "Monolitico Junquillos", detalle: "Junquillo monolítico 10 mm, sección 30×21 mm · tira 5,8 mt.", precio: 7550, precios: { blanco: 7550, "roble-nogal": 10858, "antracita-negro": 11726 }, imagen: "img/accesorios/34.jpg" },

  { id: 13, categoria: "refuerzo y cerraderos", nombre: "Refuerzo 18×28", detalle: "Refuerzo metálico en U, sección 18×28 mm.", precio: 7244, imagen: "img/accesorios/13.jpg" },
  { id: 14, categoria: "refuerzo y cerraderos", nombre: "Refuerzo 32×24", detalle: "Refuerzo metálico abierto, sección 32×24 mm.", precio: 13979, imagen: "img/accesorios/14.jpg" },
  { id: 15, categoria: "refuerzo y cerraderos", nombre: "Refuerzo 35×28", detalle: "Refuerzo metálico en U, sección 35×28 mm.", precio: 13979, imagen: "img/accesorios/15.jpg" },
  { id: 16, categoria: "refuerzo y cerraderos", nombre: "Refuerzo 50×28", detalle: "Refuerzo metálico tubular, sección 50×28 mm.", precio: 15824, imagen: "img/accesorios/16.jpg" },
  { id: 17, categoria: "refuerzo y cerraderos", nombre: "Refuerzo 12×28", detalle: "Refuerzo metálico en C, sección 12×28 mm.", precio: 7244, imagen: "img/accesorios/17.jpg" },
  { id: 35, categoria: "refuerzo y cerraderos", nombre: "Cerradero", detalle: "Cerradero metálico para cierre de hoja.", precio: 508, imagen: "img/accesorios/35.jpg" },
  { id: 36, categoria: "refuerzo y cerraderos", nombre: "Cerradero doble", detalle: "Cerradero metálico con horquilla y tope central.", precio: 530, imagen: "img/accesorios/36.jpg" },
  { id: 37, categoria: "refuerzo y cerraderos", nombre: "Cerradero con pestaña", detalle: "Cerradero metálico con pestaña y orificios.", precio: 498, imagen: "img/accesorios/37.jpg" },

  { id: 18, categoria: "manillas", nombre: "Manilla blanca", detalle: "Manilla PVC blanca con husillo cuadrado.", precio: 2045, precios: { blanco: 2045, "negro-cafe": 2210 }, imagen: "img/accesorios/18.jpg" },
  { id: 19, categoria: "manillas", nombre: "Manilla cremona blanca", detalle: "Manilla cremona blanca con husillo y postes.", precio: 5130, precios: { blanco: 5130, "negro-cafe": 5746 }, imagen: "img/accesorios/19.jpg" },
  { id: 20, categoria: "manillas", nombre: "Manilla blanca con llave", detalle: "Manilla PVC blanca con cerradura y llaves.", precio: 7824, precios: { blanco: 7824, "negro-cafe": 7956 }, imagen: "img/accesorios/20.jpg" },
  { id: 21, categoria: "manillas", nombre: "Juego manillas blancas con llave", detalle: "Par de manillas blancas con husillo y cerradura.", precio: 10999, precios: { blanco: 10999, "negro-cafe": 10990 }, imagen: "img/accesorios/21.jpg" },
  { id: 22, categoria: "manillas", nombre: "Juego manillas puerta blanca", detalle: "Par de manillas con placa larga y hueco cilindro.", precio: 19700, precios: { blanco: 19700, "negro-cafe": 20600 }, imagen: "img/accesorios/22.jpg" },
  { id: 23, categoria: "manillas", nombre: "Manilla corredera blanca", detalle: "Manilla corredera con placa y traba de pulgar.", precio: 2045, precios: { blanco: 2045, "negro-cafe": 2210 }, imagen: "img/accesorios/23.jpg" },
  { id: 38, categoria: "manillas", nombre: "Manilla multipunto blanca", detalle: "Manilla con placa larga y traba inferior.", precio: 2045, precios: { blanco: 2045, "negro-cafe": 2210 }, imagen: "img/accesorios/38.jpg" },
  { id: 39, categoria: "manillas", nombre: "Pestillo corredera blanco", detalle: "Cierre deslizante blanco para hoja corredera.", precio: 5900, precios: { blanco: 5900, "negro-cafe": 6300 }, imagen: "img/accesorios/39.jpg" },

  { id: 41, categoria: "cremonas 15mm corredera", nombre: "Cremona multipunto", detalle: "Cremona metálica con caja y leva de cierre · 180 cm.", precio: 5720, imagen: "img/accesorios/41.jpg" },
  { id: 42, categoria: "cremonas 15mm corredera", nombre: "Cremona multipunto", detalle: "Cremona metálica con caja y leva de cierre · 160 cm.", precio: 5326, imagen: "img/accesorios/42.jpg" },
  { id: 43, categoria: "cremonas 15mm corredera", nombre: "Cremona multipunto", detalle: "Cremona metálica con caja y leva de cierre · 140 cm.", precio: 4876, imagen: "img/accesorios/43.jpg" },
  { id: 44, categoria: "cremonas 15mm corredera", nombre: "Cremona multipunto", detalle: "Cremona metálica con caja y leva de cierre · 120 cm.", precio: 4697, imagen: "img/accesorios/44.jpg" },
  { id: 45, categoria: "cremonas 15mm corredera", nombre: "Cremona multipunto", detalle: "Cremona metálica con caja y leva de cierre · 100 cm.", precio: 4265, imagen: "img/accesorios/45.jpg" },
  { id: 46, categoria: "cremonas 15mm corredera", nombre: "Cremona multipunto", detalle: "Cremona metálica con caja y leva de cierre · 80 cm.", precio: 3835, imagen: "img/accesorios/46.jpg" },
  { id: 47, categoria: "cremonas 15mm corredera", nombre: "Cremona multipunto", detalle: "Cremona metálica con caja y leva de cierre · 60 cm.", precio: 3481, imagen: "img/accesorios/47.jpg" },
  { id: 48, categoria: "cremonas 15mm corredera", nombre: "Cremona multipunto", detalle: "Cremona metálica con caja y leva de cierre · 40 cm.", precio: 3150, imagen: "img/accesorios/48.jpg" },

  { id: 49, categoria: "cremonas proyectante y brazos ferritico", nombre: "Cremona proyectante", detalle: "Cremona metálica con caja y leva de cierre · 40 cm · 22 axis.", precio: 2040, imagen: "img/accesorios/49.jpg" },
  { id: 50, categoria: "cremonas proyectante y brazos ferritico", nombre: "Cremona proyectante", detalle: "Cremona metálica con caja y leva de cierre · 60 cm · 22 axis.", precio: 2271, imagen: "img/accesorios/50.jpg" },
  { id: 51, categoria: "cremonas proyectante y brazos ferritico", nombre: "Cremona proyectante", detalle: "Cremona metálica con caja y leva de cierre · 80 cm · 22 axis.", precio: 2620, imagen: "img/accesorios/51.jpg" },
  { id: 52, categoria: "cremonas proyectante y brazos ferritico", nombre: "Cremona proyectante", detalle: "Cremona metálica con caja y leva de cierre · 100 cm · 22 axis.", precio: 3106, imagen: "img/accesorios/52.jpg" },
  { id: 53, categoria: "cremonas proyectante y brazos ferritico", nombre: "Brazo ferritico proyectante", detalle: "Brazo / bisagra de fricción para ventana proyectante · 610 mm · 24/13 mm.", precio: 19470, imagen: "img/accesorios/53.jpg" },
  { id: 54, categoria: "cremonas proyectante y brazos ferritico", nombre: "Brazo ferritico proyectante", detalle: "Brazo / bisagra de fricción para ventana proyectante · 508 mm · 20/13 mm.", precio: 15724, imagen: "img/accesorios/54.jpg" },
  { id: 55, categoria: "cremonas proyectante y brazos ferritico", nombre: "Brazo ferritico proyectante", detalle: "Brazo / bisagra de fricción para ventana proyectante · 406 mm · 16/13 mm.", precio: 11574, imagen: "img/accesorios/55.jpg" },
  { id: 56, categoria: "cremonas proyectante y brazos ferritico", nombre: "Brazo ferritico proyectante", detalle: "Brazo / bisagra de fricción para ventana proyectante · 305 mm · 12/13 mm.", precio: 8288, imagen: "img/accesorios/56.jpg" },

  { id: 24, categoria: "accesorios ventanas y puertas", nombre: "Bisagra / guía blanca", detalle: "Pieza blanca con pasadores laterales para hoja · 75 mm.", precio: 1901, precios: { "blanco-negro-cafe": 1901 }, imagen: "img/accesorios/24.jpg" },
  { id: 25, categoria: "accesorios ventanas y puertas", nombre: "Bisagra bandera blanca", detalle: "Bisagra tipo bandera para ventana o puerta PVC · 3D.", precio: 9250, precios: { "blanco-negro-cafe": 9250 }, imagen: "img/accesorios/25.jpg" },
  { id: 26, categoria: "accesorios ventanas y puertas", nombre: "Tope estanco", detalle: "Tope estanco para ventana o puerta PVC.", precio: 840, precios: { "blanco-negro-cafe": 840 }, imagen: "img/accesorios/26.jpg" },
  { id: 27, categoria: "accesorios ventanas y puertas", nombre: "Carretilla doble corredera", detalle: "Rodamiento tandem para hoja corredera · 70 kg.", precio: 2708, imagen: "img/accesorios/27.jpg" },
  { id: 28, categoria: "accesorios ventanas y puertas", nombre: "Carretilla simple corredera", detalle: "Rodamiento simple ajustable para hoja corredera · 35 kg.", precio: 1603, imagen: "img/accesorios/28.jpg" },
  { id: 29, categoria: "accesorios ventanas y puertas", nombre: "Felpa / burlete 7,5×8", detalle: "Burlete de felpa para riel, sección 7,5×8 mm.", precio: 28700, imagen: "img/accesorios/29.jpg" },
  { id: 30, categoria: "accesorios ventanas y puertas", nombre: "Felpa / burlete 5,1×6,5", detalle: "Burlete de felpa para riel, sección 5,1×6,5 mm.", precio: 28700, imagen: "img/accesorios/30.jpg" },
  { id: 40, categoria: "accesorios ventanas y puertas", nombre: "Soporte / escuadra metálica", detalle: "Soporte metálico con pestañas para montaje.", precio: 1450, imagen: "img/accesorios/40.jpg" },
];
