// STOCK FRAME PVC DEPOT — edita aquí precios, medidas y fotos
// Fotos: guárdalas en la carpeta img/stock/ (01.jpg … 13.jpg)
// Precio: número sin puntos (ej. 189000). Se muestra en pesos chilenos.

window.STOCK_VENTANAS = [
  {
    id: 1,
    modelo: "Corrediza blanca",
    ancho: 1.2,
    alto: 0.9,
    precio: 165000,
    imagen: "img/stock/01.jpg",
  },
  {
    id: 2,
    modelo: "Corrediza blanca",
    ancho: 1.0,
    alto: 1.0,
    precio: 165000,
    imagen: "img/stock/02.jpg",
  },
  {
    id: 3,
    modelo: "Corrediza blanca",
    ancho: 1.1,
    alto: 1.1,
    precio: 175000,
    imagen: "img/stock/03.jpg",
  },
  {
    id: 4,
    modelo: "Corrediza blanca",
    ancho: 1.2,
    alto: 1.2,
    precio: 195000,
    imagen: "img/stock/04.jpg",
  },
  {
    id: 5,
    modelo: "Corrediza blanca",
    ancho: 1.4,
    alto: 1.2,
    precio: 245000,
    imagen: "img/stock/05.jpg",
  },
  {
    id: 6,
    modelo: "Corrediza blanca",
    ancho: 1.5,
    alto: 1.2,
    precio: 265000,
    imagen: "img/stock/06.jpg",
  },
  {
    id: 7,
    modelo: "Corrediza blanca",
    ancho: 1.5,
    alto: 1.0,
    precio: 230000,
    imagen: "img/stock/07.jpg",
  },
  {
    id: 8,
    modelo: "Corrediza blanca",
    ancho: 1.5,
    alto: 1.5,
    precio: 330000,
    imagen: "img/stock/08.jpg",
  },
  {
    id: 9,
    modelo: "Corrediza blanca",
    ancho: 1.5,
    alto: 2.0,
    precio: 390000,
    imagen: "img/stock/09.jpg",
  },
  {
    id: 10,
    modelo: "Corrediza blanca",
    ancho: 0.9,
    alto: 0.7,
    precio: 135000,
    imagen: "img/stock/10.jpg",
  },
  {
    id: 11,
    modelo: "Proyectante blanca",
    ancho: 0.6,
    alto: 0.6,
    precio: 85000,
    imagen: "img/stock/11.jpg",
  },
  {
    id: 12,
    modelo: "Proyectante blanca",
    ancho: 0.98,
    alto: 0.6,
    precio: 135000,
    imagen: "img/stock/12.jpg",
  },
  {
    id: 13,
    modelo: "Proyectante blanca",
    ancho: 0.98,
    alto: 0.89,
    precio: 145000,
    imagen: "img/stock/13.jpg",
  },
];
