(() => {
  "use strict";
  const WHATSAPP = "56950187327";
  const STORAGE_KEY = "frame-pvc-inventario-seleccion";
  const $ = (selector, root = document) => root.querySelector(selector);
  const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
  const money = (value) => `$${Number(value || 0).toLocaleString("es-CL")}`;
  const clean = (value = "") => String(value).normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim();
  const safe = (value = "") => String(value).replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char]);
  const optimizedImage = (path) => { const match = String(path).match(/img\/(stock|accesorios)\/(\d+)\.jpg$/i); return match ? `img/catalog/${match[1] === "stock" ? "stock" : "accessory"}-${match[2]}.webp` : path; };
  const categoryLabels = { ventanas: "Ventanas", perfiles: "Perfiles PVC", manillas: "Manillas", cremonas: "Cremonas", refuerzos: "Refuerzos", accesorios: "Accesorios" };
  const colorLabels = { blanco: "Blanco", nogal: "Nogal", roble: "Roble dorado", antracita: "Antracita", negro: "Negro", cafe: "Café" };
  const availabilityLabels = { confirmado: "Stock confirmado", consultar: "Consultar disponibilidad" };
  const typeOf = (text) => ["corredera", "proyectante", "fija", "puerta"].find((type) => clean(text).includes(type)) || "";
  const accessoryCategory = (item) => { const category = clean(item.categoria); if (category.includes("perfil")) return "perfiles"; if (category.includes("manilla")) return "manillas"; if (category.includes("cremona")) return "cremonas"; if (category.includes("refuerzo") || category.includes("cerradero")) return "refuerzos"; return "accesorios"; };
  const variantLabel = (key) => ({ blanco: "Blanco", "roble-nogal": "Roble dorado / Nogal", "antracita-negro": "Antracita / Negro", "negro-cafe": "Negro / Café", "blanco-negro-cafe": "Blanco / Negro / Café" })[key] || key.replaceAll("-", " / ");
  const variantColors = (key) => Object.keys(colorLabels).filter((color) => clean(key).includes(color));
  const inferUnit = (item, category) => { const text = clean(`${item.nombre} ${item.detalle}`); if (text.includes("tira") || category === "perfiles") return "Tira"; if (text.includes("juego") || text.includes("par de")) return "Juego"; if (text.includes("felpa") || text.includes("burlete")) return "Rollo"; return "Unidad"; };

  const products = [
    ...(window.STOCK_VENTANAS || []).map((item) => ({ id: `window-${item.id}`, group: "VENTANAS", category: "ventanas", type: typeOf(item.modelo), name: item.modelo, detail: "Ventana PVC termopanel lista para entrega", price: Number(item.precio), image: optimizedImage(item.imagen), width: Math.round(Number(item.ancho) * 100), height: Math.round(Number(item.alto) * 100), colors: ["blanco"], availability: "confirmado", unit: "Unidad", variants: [] })),
    ...(window.STOCK_ACCESORIOS || []).map((item) => { const category = accessoryCategory(item); const variants = Object.entries(item.precios || {}).map(([key, price]) => ({ id: key, label: variantLabel(key), price: Number(price), colors: variantColors(key) })); return { id: `accessory-${item.id}`, group: category === "perfiles" ? "PERFILES" : "ACCESORIOS", category, type: typeOf(`${item.categoria} ${item.nombre}`), name: item.nombre, detail: item.detalle, price: variants.length ? Math.min(...variants.map((variant) => variant.price)) : Number(item.precio), image: optimizedImage(item.imagen), width: null, height: null, colors: [...new Set(variants.flatMap((variant) => variant.colors))], availability: "consultar", unit: inferUnit(item, category), variants }; }),
  ];
  const state = { query: "", category: "todos", types: new Set(), colors: new Set(), availability: new Set(), maxPrice: 400000, width: 0, height: 0, sort: "relevance", limit: innerWidth < 720 ? 8 : 12, selection: loadSelection(), compare: [], current: null };
  const aliases = { corredera: ["corredera", "corrediza"], corrediza: ["corrediza", "corredera"], ventana: ["ventana", "ventanas"], perfil: ["perfil", "perfiles", "marco"], tirador: ["tirador", "manilla"], manija: ["manija", "manilla"], cierre: ["cierre", "cerradero", "cremona"] };

  function loadSelection() { try { const value = JSON.parse(localStorage.getItem(STORAGE_KEY)); return Array.isArray(value) ? value : []; } catch { return []; } }
  function saveSelection() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state.selection)); } catch { /* Storage puede estar deshabilitado. */ } }
  function searchable(product) { return clean([product.name, product.detail, categoryLabels[product.category], product.type, product.unit, product.width && `${product.width} ${product.height} ${product.width}x${product.height}`, ...product.colors.map((color) => colorLabels[color])].filter(Boolean).join(" ")); }
  function matches(product, query = state.query) { return clean(query).replace(/(\d)\s*[x×]\s*(\d)/g, "$1x$2").split(/\s+/).filter(Boolean).every((term) => (aliases[term] || [term]).some((candidate) => searchable(product).includes(candidate))); }
  function filteredProducts() { return products.filter((product) => matches(product) && (state.category === "todos" || product.category === state.category) && (!state.types.size || state.types.has(product.type)) && (!state.colors.size || [...state.colors].some((color) => product.colors.includes(color))) && (!state.availability.size || state.availability.has(product.availability)) && product.price <= state.maxPrice && (!state.width || (product.width && product.width >= state.width)) && (!state.height || (product.height && product.height >= state.height))).sort((a, b) => state.sort === "price-asc" ? a.price - b.price : state.sort === "price-desc" ? b.price - a.price : state.sort === "name" ? a.name.localeCompare(b.name, "es") : state.sort === "measure" ? (a.width || Infinity) - (b.width || Infinity) : products.indexOf(a) - products.indexOf(b)); }
  function measure(product) { return product.width ? `${product.width} × ${product.height} cm` : ""; }
  function variants(product) { return product.variants.length ? product.variants : [{ id: "base", label: product.colors.length ? product.colors.map((color) => colorLabels[color]).join(" / ") : "Estándar", price: product.price }]; }

  function productCard(product, index = 0) {
    const selected = state.compare.includes(product.id), productMeasure = measure(product);
    return `<article class="inventory-card" style="--card-index:${index}"><button class="inventory-photo" type="button" data-review="${safe(product.id)}" aria-label="Revisar ${safe(product.name)}"><img src="${safe(product.image)}" width="420" height="336" loading="lazy" alt="${safe(product.name)}"><span>${safe(availabilityLabels[product.availability])}</span></button><div class="inventory-card-body"><small class="inventory-category">${safe(categoryLabels[product.category])}</small><h2>${safe(product.name)}</h2><p class="inventory-description">${safe(product.detail)}</p><div class="inventory-specs">${productMeasure ? `<span>${safe(productMeasure)} · ${safe(product.unit)}</span>` : `<span>${safe(product.unit)}${product.variants.length ? ` · ${product.variants.length} variantes` : ""}</span>`}</div><div class="inventory-price"><strong>${product.variants.length > 1 ? "Desde " : ""}${money(product.price)}</strong><small>12 cuotas ref. de ${money(Math.ceil(product.price / 12))}</small></div><div class="inventory-card-actions"><button type="button" data-compare="${safe(product.id)}" aria-pressed="${selected}">${selected ? "✓ Revisando" : "+ Comparar"}</button><button class="review-button" type="button" data-review="${safe(product.id)}">Revisar producto</button></div></div></article>`;
  }
  let productTransition;
  function renderProducts(reset = false) {
    if (reset) state.limit = innerWidth < 720 ? 8 : 12;
    const update = () => {
      const results = filteredProducts(), shown = results.slice(0, state.limit);
      $("#inventory-grid").innerHTML = shown.map(productCard).join("");
      $("#inventory-results").textContent = `${results.length} productos · mostrando ${shown.length}`;
      $("#inventory-empty").hidden = results.length !== 0;
      $("#inventory-more").hidden = shown.length >= results.length;
      renderActive();
    };
    const gridHasProducts = Boolean($("#inventory-grid").children.length);
    const reduceMotion = matchMedia("(prefers-reduced-motion: reduce)").matches;
    if (!gridHasProducts || reduceMotion || typeof document.startViewTransition !== "function") { update(); return; }
    productTransition?.skipTransition();
    const transition = document.startViewTransition(update);
    productTransition = transition;
    transition.finished.finally(() => { if (productTransition === transition) productTransition = null; });
  }
  function renderActive() { const active = []; if (state.query) active.push(`“${state.query}”`); if (state.category !== "todos") active.push(categoryLabels[state.category]); active.push(...state.types, ...[...state.colors].map((color) => colorLabels[color]), ...[...state.availability].map((item) => availabilityLabels[item])); $("#inventory-active").innerHTML = active.map((label) => `<span>${safe(label)}</span>`).join(""); $("#inventory-filter-count").textContent = active.length; }
  function filterMarkup(name, values, labels) { return values.map((value) => `<label><input type="checkbox" name="${name}" value="${safe(value)}"> ${safe(labels[value] || value)}</label>`).join(""); }
  function renderFilters() { $("#inventory-types").innerHTML = filterMarkup("type", ["corredera", "proyectante", "fija", "puerta"], { corredera: "Corredera", proyectante: "Proyectante", fija: "Fija", puerta: "Puerta" }); $("#inventory-colors").innerHTML = filterMarkup("color", Object.keys(colorLabels), colorLabels); $("#inventory-availability").innerHTML = filterMarkup("availability", Object.keys(availabilityLabels), availabilityLabels); }
  function renderSuggestions() { const value = $("#inventory-query").value.trim(), panel = $("#inventory-suggestions"); if (value.length < 2) { panel.hidden = true; return; } const matchesList = products.filter((product) => matches(product, value)).slice(0, 6); panel.innerHTML = matchesList.length ? matchesList.map((product) => `<button type="button" data-suggestion="${safe(product.name)}"><img src="${safe(product.image)}" alt=""><span><b>${safe(product.name)}</b><small>${safe(categoryLabels[product.category])} · ${money(product.price)}</small></span></button>`).join("") : "<p>No encontramos coincidencias.</p>"; panel.hidden = false; }

  function renderReview(product) { state.current = product; $("#product-review-title").textContent = product.name; const productVariants = variants(product), productMeasure = measure(product); $("#product-review-content").innerHTML = `<div class="review-image"><img src="${safe(product.image)}" alt="${safe(product.name)}"></div><div class="review-copy"><span class="inventory-category">${safe(categoryLabels[product.category])}</span><p>${safe(product.detail)}</p><dl class="review-specs">${productMeasure ? `<div><dt>Medida</dt><dd>${safe(productMeasure)}</dd></div>` : ""}<div><dt>Unidad</dt><dd>${safe(product.unit)}</dd></div><div><dt>Disponibilidad</dt><dd>${safe(availabilityLabels[product.availability])}</dd></div></dl><label class="review-choice">Variante<select id="review-variant">${productVariants.map((variant) => `<option value="${safe(variant.id)}" data-price="${variant.price}">${safe(variant.label)} — ${money(variant.price)}</option>`).join("")}</select></label><div class="review-purchase"><div><small>Precio unitario</small><strong id="review-price">${money(productVariants[0].price)}</strong></div><label>Cantidad<input id="review-qty" type="number" min="1" max="99" value="1"></label></div><button class="review-add" id="review-add" type="button">Agregar a mi selección</button></div>`; openPanel("review"); }
  function addCurrent() { const product = state.current; if (!product) return; const select = $("#review-variant"), option = select.selectedOptions[0], qty = Math.max(1, Math.min(99, Number($("#review-qty").value) || 1)), id = `${product.id}-${select.value}`; const existing = state.selection.find((item) => item.id === id); if (existing) existing.qty = Math.min(99, existing.qty + qty); else state.selection.push({ id, name: product.name, detail: [measure(product), product.unit, option.textContent.split(" — ")[0]].filter(Boolean).join(" · "), price: Number(option.dataset.price), image: product.image, qty }); saveSelection(); renderSelection(); toast("Producto agregado a tu selección"); closePanels(); }
  function renderSelection() { const count = state.selection.reduce((sum, item) => sum + item.qty, 0); $$('[data-selection-count]').forEach((element) => { element.textContent = count; }); $("#selection-items").innerHTML = count ? state.selection.map((item) => `<article class="selection-item"><img src="${safe(item.image)}" alt=""><div><h3>${safe(item.name)}</h3><p>${safe(item.detail)}</p><strong>${money(item.price * item.qty)}</strong><div class="selection-item-actions"><button data-qty="-1" data-id="${safe(item.id)}">−</button><span>${item.qty}</span><button data-qty="1" data-id="${safe(item.id)}">+</button></div></div><button data-remove="${safe(item.id)}" aria-label="Eliminar">×</button></article>`).join("") : '<div class="selection-empty"><p>Aún no has seleccionado productos.</p></div>'; const total = state.selection.reduce((sum, item) => sum + item.price * item.qty, 0), link = $("#selection-whatsapp"); $("#selection-total").textContent = money(total); link.setAttribute("aria-disabled", String(!count)); link.href = count ? `https://wa.me/${WHATSAPP}?text=${encodeURIComponent(selectionMessage(total))}` : "#"; }
  function selectionMessage(total) { return ["Hola, quiero consultar estos productos de FRAME PVC DEPOT:", "", ...state.selection.flatMap((item) => [`${item.qty} × ${item.name}`, item.detail, money(item.price * item.qty), ""]), "TOTAL REFERENCIAL", money(total), "", "Quisiera confirmar disponibilidad, variantes y despacho."].join("\n"); }

  function toggleCompare(id) { state.compare = state.compare.includes(id) ? state.compare.filter((item) => item !== id) : state.compare.length < 3 ? [...state.compare, id] : state.compare; if (state.compare.length === 3 && !state.compare.includes(id)) toast("Puedes comparar hasta 3 productos"); renderCompare(); renderProducts(); }
  function renderCompare() { const selected = state.compare.map((id) => products.find((product) => product.id === id)).filter(Boolean); $("#compare-bar").hidden = !selected.length; $("#compare-status").textContent = `${selected.length} de 3 seleccionados`; $("#compare-open").disabled = selected.length < 2; $("#compare-content").innerHTML = selected.length < 2 ? "<p>Selecciona al menos dos productos.</p>" : `<div class="compare-table">${[["Producto", (p) => `<img src="${safe(p.image)}" alt=""><strong>${safe(p.name)}</strong>`], ["Precio", (p) => money(p.price)], ["Medida", (p) => measure(p) || "No aplica"], ["Categoría", (p) => categoryLabels[p.category]], ["Unidad", (p) => p.unit], ["Disponibilidad", (p) => availabilityLabels[p.availability]], ["Variantes", (p) => p.variants.length || "Estándar"]].map(([label, value]) => `<div class="compare-row"><b>${label}</b>${selected.map((product) => `<span>${value(product)}</span>`).join("")}</div>`).join("")}</div>`; }
  function openPanel(name) { closePanels(); $("#inventory-overlay").hidden = false; document.body.classList.add("is-locked"); const panel = name === "review" ? $("#product-review") : $("#selection-drawer"); panel.classList.add("is-open"); panel.setAttribute("aria-hidden", "false"); }
  function closePanels() { $("#inventory-overlay").hidden = true; document.body.classList.remove("is-locked"); [$("#product-review"), $("#selection-drawer")].forEach((panel) => { panel.classList.remove("is-open"); panel.setAttribute("aria-hidden", "true"); }); }
  function updateSearchMode() {
    const searching = Boolean(clean(state.query));
    document.body.classList.toggle("inventory-searching", searching);
    if (!searching) return;
    state.types.clear(); state.colors.clear(); state.availability.clear(); state.maxPrice = 400000; state.width = 0; state.height = 0;
    $$('#inventory-filters input[type="checkbox"]').forEach((input) => { input.checked = false; });
    $("#inventory-price").value = 400000; $("#inventory-price-output").textContent = money(400000); $("#inventory-width").value = ""; $("#inventory-height").value = "";
    $("#inventory-filters").classList.remove("is-open"); $("#inventory-filter-trigger").setAttribute("aria-expanded", "false");
  }
  function clearFilters() { state.query = ""; state.category = "todos"; state.types.clear(); state.colors.clear(); state.availability.clear(); state.maxPrice = 400000; state.width = 0; state.height = 0; $("#inventory-query").value = ""; $$('#inventory-filters input[type="checkbox"]').forEach((input) => { input.checked = false; }); $("#inventory-price").value = 400000; $("#inventory-price-output").textContent = money(400000); $("#inventory-width").value = ""; $("#inventory-height").value = ""; $$('[data-category]').forEach((button) => button.classList.toggle("is-active", button.dataset.category === "todos")); updateSearchMode(); renderProducts(true); }
  let toastTimer; function toast(text) { const element = $("#inventory-toast"); element.textContent = text; element.classList.add("is-visible"); clearTimeout(toastTimer); toastTimer = setTimeout(() => element.classList.remove("is-visible"), 2200); }

  function bindEvents() {
    const menu = $("#inventory-menu-toggle"), nav = $("#inventory-nav"), navOverlay = $("#inventory-nav-overlay"); const closeMenu = () => { menu.setAttribute("aria-expanded", "false"); nav.classList.remove("is-open"); navOverlay.hidden = true; }; menu.addEventListener("click", () => { const open = menu.getAttribute("aria-expanded") !== "true"; menu.setAttribute("aria-expanded", String(open)); nav.classList.toggle("is-open", open); navOverlay.hidden = !open; }); navOverlay.addEventListener("click", closeMenu); nav.addEventListener("click", closeMenu);
    $("#inventory-search").addEventListener("submit", (event) => { event.preventDefault(); state.query = $("#inventory-query").value.trim(); updateSearchMode(); $("#inventory-suggestions").hidden = true; renderProducts(true); }); $("#inventory-query").addEventListener("input", (event) => { state.query = event.target.value; updateSearchMode(); renderSuggestions(); renderProducts(true); });
    $("#inventory-categories").addEventListener("click", (event) => { const button = event.target.closest("[data-category]"); if (!button) return; state.query = ""; $("#inventory-query").value = ""; $("#inventory-suggestions").hidden = true; updateSearchMode(); state.category = button.dataset.category; $$('[data-category]').forEach((item) => item.classList.toggle("is-active", item === button)); renderProducts(true); });
    $("#inventory-filters").addEventListener("change", (event) => { const map = { type: state.types, color: state.colors, availability: state.availability }, set = map[event.target.name]; if (set) event.target.checked ? set.add(event.target.value) : set.delete(event.target.value); renderProducts(true); });
    $("#inventory-price").addEventListener("input", (event) => { state.maxPrice = Number(event.target.value); $("#inventory-price-output").textContent = money(state.maxPrice); renderProducts(true); }); $("#inventory-width").addEventListener("input", (event) => { state.width = Number(event.target.value) || 0; renderProducts(true); }); $("#inventory-height").addEventListener("input", (event) => { state.height = Number(event.target.value) || 0; renderProducts(true); }); $("#inventory-sort").addEventListener("change", (event) => { state.sort = event.target.value; renderProducts(); });
    $("#inventory-more").addEventListener("click", () => { state.limit += innerWidth < 720 ? 8 : 12; renderProducts(); }); $("#inventory-clear").addEventListener("click", clearFilters); $("[data-clear-all]").addEventListener("click", clearFilters);
    const toggleFilters = (open) => { $("#inventory-filters").classList.toggle("is-open", open); $("#inventory-filter-trigger").setAttribute("aria-expanded", String(open)); }; $("#inventory-filter-trigger").addEventListener("click", () => toggleFilters(!$("#inventory-filters").classList.contains("is-open"))); $("#inventory-filter-close").addEventListener("click", () => toggleFilters(false)); $$('[data-open-filters]').forEach((button) => button.addEventListener("click", () => toggleFilters(true)));
    document.addEventListener("click", (event) => { const suggestion = event.target.closest("[data-suggestion]"); if (suggestion) { $("#inventory-query").value = suggestion.dataset.suggestion; state.query = suggestion.dataset.suggestion; updateSearchMode(); $("#inventory-suggestions").hidden = true; renderProducts(true); return; } const review = event.target.closest("[data-review]"); if (review) { renderReview(products.find((product) => product.id === review.dataset.review)); return; } const compare = event.target.closest("[data-compare]"); if (compare) { toggleCompare(compare.dataset.compare); return; } if (event.target.closest("[data-open-selection]")) openPanel("selection"); if (event.target.closest("[data-close-panel]")) closePanels(); if (event.target.closest("[data-focus-search]")) { $("#inventory-query").focus(); scrollTo({ top: 0, behavior: "smooth" }); } });
    $("#inventory-overlay").addEventListener("click", closePanels); $("#product-review-content").addEventListener("change", (event) => { if (event.target.id === "review-variant") $("#review-price").textContent = money(event.target.selectedOptions[0].dataset.price); }); $("#product-review-content").addEventListener("click", (event) => { if (event.target.id === "review-add") addCurrent(); });
    $("#selection-items").addEventListener("click", (event) => { const qty = event.target.closest("[data-qty]"), remove = event.target.closest("[data-remove]"); if (qty) { const item = state.selection.find((entry) => entry.id === qty.dataset.id); if (item) item.qty += Number(qty.dataset.qty); if (item?.qty < 1) state.selection = state.selection.filter((entry) => entry.id !== item.id); } if (remove) state.selection = state.selection.filter((entry) => entry.id !== remove.dataset.remove); if (qty || remove) { saveSelection(); renderSelection(); } });
    $("#compare-open").addEventListener("click", () => $("#inventory-compare").showModal()); $("#compare-close").addEventListener("click", () => $("#inventory-compare").close()); $("#compare-clear").addEventListener("click", () => { state.compare = []; renderCompare(); renderProducts(); }); document.addEventListener("keydown", (event) => { if (event.key === "Escape") closePanels(); });
  }

  renderFilters(); bindEvents(); renderProducts(); renderSelection(); renderCompare();
})();
